# Generated by Django 4.1.3 on 2022-11-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
